### ISSUE TITLE
Support for 6.8.6

### ISSUE THREAD

**Issue by apristen** [elo7/cohort#25]
Trying to install and got this:
```
bash-4.2$ kibana-plugin install https://github.com/elo7/cohort/releases/download/6.2.3/cohort-6.2.3.zip
Attempting to transfer from https://github.com/elo7/cohort/releases/download/6.2.3/cohort-6.2.3.zip
Transferring 6099 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin cohort [6.2.3] is incompatible with Kibana [6.8.6]"
```

What to do? How to install on Kibana 6.8.6 ?

**Comment by sergolius** [comment]
hello @apristen Kibana expects strict equal of plugin and Kibana version.
In opposite of install plugin via CLI you are able to add source code manually.

https://github.com/elo7/cohort/issues/18#issuecomment-438593943

**Comment by apristen** [comment]
thanks @sergolius !

I'm trying **manual distribution** from readme.md 

```
export VERSION=6.8.6
export GITHUB_TOKEN=<my_github_token_with_repo_access>

npm install

node_modules/release-it/bin/release.js $VERSION  -e
node_modules/publish-release/bin/publish-release --token $GITHUB_TOKEN --owner elo7 --repo cohort --assets build/cohort-$VERSION.zip --tag $VERSION --name $VERSION --notes 'Release for Kibana '$VERSION''
```

and it asks me username and password and then fails with my username:
```
WARNING Latest Git tag (6.2.3) doesn't match package.json#version (6.3.2).
* Merge pull request #20 from sergolius/rc-6.3.2 (77bb52e)
* feature: support kibana 6.4.0 (4c51c53)
* - feature: added support Kibana 6.3.x - droped support Kibana 5.x - prettify, eslint - droped angular, move to VanillaJS - updated package.json (34e97c9)
* Update README.md (709a71d)
? Ready to release 6.8.6? Yes
? Show staged files? No
? Commit (Release 6.8.6)? Yes
? Tag (6.8.6)? Yes
? Push? Yes
Username for 'https://github.com':
Password for 'https://github.com':
ERROR warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/elo7/cohort.git/'
```

Should I clone this repo to my account to release for Kibana 6.8.6 ?

**Comment by apristen** [comment]
I changed numbers in package.json of 6.2.3 release and try to install on 6.8.6 and got this:

`bash-4.2$ kibana-plugin install http://10.8.0.14/cohort-6.8.6.zip
Attempting to transfer from http://10.8.0.14/cohort-6.8.6.zip
Transferring unknown number of bytes
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...

Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

 FATAL  Error: Optimizations failure.
   5628 modules

    ERROR in ./plugins/cohort/public/cohort.js
    Module not found: Error: Can't resolve 'ui/vis/vis_category' in '/usr/share/kibana/plugins/cohort/public'



{"type":"log","@timestamp":"2020-05-04T11:59:56Z","tags":["info","plugins-service"],"pid":632,"message":"Plugin initialization disabled."}
{"type":"log","@timestamp":"2020-05-04T12:00:03Z","tags":["info","optimize"],"pid":632,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
{"type":"log","@timestamp":"2020-05-04T12:01:07Z","tags":["fatal","root"],"pid":632,"message":"{ Error: Optimizations failure.\n   5628 modules\n    \n    ERROR in ./plugins/cohort/public/cohort.js\n    Module not found: Error: Can't resolve 'ui/vis/vis_category' in '/usr/share/kibana/plugins/cohort/public'\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:461:27)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:45:26)\n    at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:210:39)\n    at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:226:13)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:224:21)\n    at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:552:14)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:549:30)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1312:35)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at hooks.optimizeChunkAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1303:32)\n    at _err1 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:20:1)\n    at taskRunner.run (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/index.js:315:9)\n    at step (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:76:9)\n    at done (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:84:30)\n    at boundWorkers (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:13)\n  cause:\n   { Error: Optimizations failure.\n      5628 modules\n       \n       ERROR in ./plugins/cohort/public/cohort.js\n       Module not found: Error: Can't resolve 'ui/vis/vis_category' in '/usr/share/kibana/plugins/cohort/public'\n   \n       at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:461:27)\n       at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:45:26)\n       at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:210:39)\n       at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:226:13)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:224:21)\n       at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:552:14)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:549:30)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1312:35)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at hooks.optimizeChunkAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1303:32)\n       at _err1 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:20:1)\n       at taskRunner.run (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/index.js:315:9)\n       at step (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:76:9)\n       at done (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:84:30)\n       at boundWorkers (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:13)\n     data:\n      { errors: [Array],\n        warnings: [],\n        version: '4.23.1',\n        hash: 'd7dafb6496f83b77777a',\n        time: 63379,\n        builtAt: 1588593667120,\n        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n        outputPath: '/usr/share/kibana/optimize/bundles',\n        assetsByChunkName: [Object],\n        assets: [Array],\n        filteredAssets: 0,\n        entrypoints: [Object],\n        namedChunkGroups: [Object],\n        chunks: [Array],\n        modules: [Array],\n        filteredModules: 0,\n        children: [Array] },\n     isBoom: true,\n     isServer: true,\n     output: { statusCode: 500, payload: [Object], headers: {} },\n     reformat: [Function],\n     typeof: [Function: internal] },\n  isOperational: true,\n  data:\n   { errors:\n      [ './plugins/cohort/public/cohort.js\\nModule not found: Error: Can\\'t resolve \\'ui/vis/vis_category\\' in \\'/usr/share/kibana/plugins/cohort/public\\'\\nresolve \\'ui/vis/vis_category\\' in \\'/usr/share/kibana/plugins/cohort/public\\'\\n  Parsed request is a module\\n  using description file: /usr/share/kibana/plugins/cohort/package.json (relative path: ./public)\\n    aliased with mapping \\'ui\\': \\'/usr/share/kibana/src/ui/public\\' to \\'/usr/share/kibana/src/ui/public/vis/vis_category\\'\\n      using description file: /usr/share/kibana/plugins/cohort/package.json (relative path: ./public)\\n        Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n        using description file: /usr/share/kibana/package.json (relative path: ./src/ui/public/vis/vis_category)\\n          no extension\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/ui/public/vis/vis_category doesn\\'t exist\\n          .js\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/ui/public/vis/vis_category.js doesn\\'t exist\\n          .json\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/ui/public/vis/vis_category.json doesn\\'t exist\\n          as directory\\n            /usr/share/kibana/src/ui/public/vis/vis_category doesn\\'t exist\\n[/usr/share/kibana/src/ui/public/vis/vis_category]\\n[/usr/share/kibana/src/ui/public/vis/vis_category.js]\\n[/usr/share/kibana/src/ui/public/vis/vis_category.json]\\n @ ./plugins/cohort/public/cohort.js 15:20-50\\n @ ./node_modules/val-loader/dist/cjs.js!./src/optimize/create_ui_exports_module.js?{\"type\":\"visTypes\",\"modules\":[\"plugins/tilemap/vis_type_enhancers/update_tilemap_settings\",\"plugins/cohort/cohort\",\"plugins/input_control_vis/register_vis\",\"plugins/kbn_vislib_vis_types/kbn_vislib_vis_types\",\"plugins/markdown_vis/markdown_vis\",\"plugins/metric_vis/metric_vis\",\"plugins/metrics/kbn_vis_types\",\"plugins/region_map/region_map_vis\",\"plugins/table_vis/table_vis\",\"plugins/tagcloud/tag_cloud_vis\",\"plugins/timelion/vis\",\"plugins/tile_map/tile_map_vis\",\"plugins/vega/vega_type\"]}\\n @ ./node_modules/x-pack/plugins/canvas/public/app.js\\n @ ./optimize/bundles/canvas.entry.js' ],\n     warnings: [],\n     version: '4.23.1',\n     hash: 'd7dafb6496f83b77777a',\n     time: 63379,\n     builtAt: 1588593667120,\n     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n     outputPath: '/usr/share/kibana/optimize/bundles',\n     assetsByChunkName:\n      { commons: [Array],\n        apm: [Array],\n        canvas: [Array],\n        dashboardViewer: 'dashboardViewer.bundle.js',\n        graph: 'graph.bundle.js',\n        infra: 'infra.bundle.js',\n        kibana: [Array],\n        logged_out: [Array],\n        login: [Array],\n        logout: 'logout.bundle.js',\n        maps: [Array],\n        ml: [Array],\n        monitoring: [Array],\n        space_selector: [Array],\n        stateSessionStorageRedirect: 'stateSessionStorageRedirect.bundle.js',\n        status_page: 'status_page.bundle.js',\n        timelion: 'timelion.bundle.js',\n        uptime: 'uptime.bundle.js' },\n     assets:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     filteredAssets: 0,\n     entrypoints:\n      { graph: [Object],\n        monitoring: [Object],\n        space_selector: [Object],\n        login: [Object],\n        logout: [Object],\n        logged_out: [Object],\n        ml: [Object],\n        dashboardViewer: [Object],\n        apm: [Object],\n        maps: [Object],\n        canvas: [Object],\n        infra: [Object],\n        uptime: [Object],\n        kibana: [Object],\n        stateSessionStorageRedirect: [Object],\n        status_page: [Object],\n        timelion: [Object] },\n     namedChunkGroups:\n      { graph: [Object],\n        monitoring: [Object],\n        space_selector: [Object],\n        login: [Object],\n        logout: [Object],\n        logged_out: [Object],\n        ml: [Object],\n        dashboardViewer: [Object],\n        apm: [Object],\n        maps: [Object],\n        canvas: [Object],\n        infra: [Object],\n        uptime: [Object],\n        kibana: [Object],\n        stateSessionStorageRedirect: [Object],\n        status_page: [Object],\n        timelion: [Object] },\n     chunks:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     modules:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        ... 5528 more items ],\n     filteredModules: 0,\n     children:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ] },\n  isBoom: true,\n  isServer: true,\n  output:\n   { statusCode: 500,\n     payload:\n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: internal] }"}
"
`

**Comment by sergolius** [comment]
@apristen You don't have to install plugin. You able to copy source code of plugin(directory) into `plugins` directory of Kibana's.
Kibana asserts it's own version with version of plugin from `package.json`.
To skip this assert write/override to `package.json`:
```
"kibana": {
  "version": "kibana"
},
```

Kibana again changed API, here is source code with fix (tested on Kibana 6.8.6): https://github.com/sergolius/cohort/tree/6.6.x

how to generate test payload/index: https://github.com/elo7/cohort/issues/10

**Comment by phgn0** [comment]
Thank you very much @sergolius for creating the fork! 
The following code installs cohort for kibana 6.8.1, works great for me:
```
curl -Ls https://github.com/sergolius/cohort/archive/6.6.x.tar.gz | tar -xzf - -C ./plugins
sed -i 's/6.5.0/6.8.1/g' ./plugins/cohort-6.6.x/package.json
```
